services:
  postgres:
    image: postgres:15-alpine
    container_name: quiz_builder_postgres
    environment:
      POSTGRES_USER: quiz_builder
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiz_builder_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U quiz_builder -d quiz_builder_development"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz_builder_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://quiz_builder:password@postgres:5432/quiz_builder_development
      - RAILS_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "bundle install &&
               bundle exec rails db:create db:migrate db:seed &&
               bundle exec rails server -b 0.0.0.0"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiz_builder_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000

volumes:
  postgres_data:
  bundle_cache:
